name: Linting & formatting code & content

on: [push]

jobs:
  format-all:
    name: Format code & content
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install NPM dependencies
        run: npm ci --prefer-offline

      - name: Check formatting using Prettier
        run: npx prettier -c .
